backbone: resnet34
batch_size: 1
fast_dev_run: false
gpu: true
hparams:
  backbone: resnet34
  batch_size: 1
  fast_dev_run: false
  gpu: true
  in_channels: 8
  log_path: tensorboard_logs
  lr: 0.001
  max_epochs: 1000
  min_epochs: 4
  num_workers: 16
  out_channels: 25
  output_path: model-outputs
  patience: 10
  test_dataset: &id001 !!python/object:ImgDataset.TestDataset
    data:
    - 0001.npz
    - 0003.npz
    - 0005.npz
    feature_path: ./data/test/feature
    label_path: ./data/test/label
  val_sanity_checks: 0
  weights: imagenet
in_channels: 8
log_path: tensorboard_logs
lr: 0.001
max_epochs: 1000
min_epochs: 4
num_workers: 16
out_channels: 25
output_path: model-outputs
patience: 10
test_dataset: *id001
val_sanity_checks: 0
weights: imagenet
